bundles:
  hello-world:
    object_storage:
      aws:
        bucket: bundles
        key: hello-world
        region: us-east-1
        url: http://localstack:4566
        credentials: s3-creds
    requirements:
    - source: git-policies
sources:
  git-policies:
    git:
      repo: https://github.com/open-policy-agent/contrib
      commit: 0f81d9a0018451d98dcd3f4bb885ee676f49f6fe
      included_files:
      - k8s_authorization/policy/policy.rego
tokens:
  admin:
    api_key: sesame
    scopes:
    - role: administrator
database:
  sql:
    driver: postgres
    dsn: postgresql://postgres:sesame@db:5432
    credentials: pg-tls
secrets:
  s3-creds:
    type: aws_auth
    access_key_id: doesnotmatter
    secret_access_key: doesnotmatter
  pg-tls:
    type: tls_cert
    tls_cert: ${OCP_TLS_CERT}
    tls_key: ${OCP_TLS_KEY}
